/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SolidityTypes_pb = require('./SolidityTypes_pb.js');
goog.object.extend(proto, SolidityTypes_pb);
goog.exportSymbol('proto.BorrowingEngagementProperty', null, global);
goog.exportSymbol('proto.BorrowingEngagementProperty.LoanState', null, global);
goog.exportSymbol('proto.BorrowingIssuanceProperty', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.BorrowingIssuanceProperty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.BorrowingIssuanceProperty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.BorrowingIssuanceProperty.displayName = 'proto.BorrowingIssuanceProperty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.BorrowingEngagementProperty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.BorrowingEngagementProperty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.BorrowingEngagementProperty.displayName = 'proto.BorrowingEngagementProperty';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.BorrowingIssuanceProperty.prototype.toObject = function(opt_includeInstance) {
  return proto.BorrowingIssuanceProperty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.BorrowingIssuanceProperty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingIssuanceProperty.toObject = function(includeInstance, msg) {
  var f, obj = {
    borrowingtokenaddress: (f = msg.getBorrowingtokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    collateraltokenaddress: (f = msg.getCollateraltokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    borrowingamount: (f = msg.getBorrowingamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    collateralratio: (f = msg.getCollateralratio()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    collateralamount: (f = msg.getCollateralamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    interestrate: (f = msg.getInterestrate()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    interestamount: (f = msg.getInterestamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    tenordays: (f = msg.getTenordays()) && SolidityTypes_pb.uint256.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.BorrowingIssuanceProperty}
 */
proto.BorrowingIssuanceProperty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.BorrowingIssuanceProperty;
  return proto.BorrowingIssuanceProperty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.BorrowingIssuanceProperty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.BorrowingIssuanceProperty}
 */
proto.BorrowingIssuanceProperty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setBorrowingtokenaddress(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setCollateraltokenaddress(value);
      break;
    case 3:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setBorrowingamount(value);
      break;
    case 4:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCollateralratio(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCollateralamount(value);
      break;
    case 6:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setInterestrate(value);
      break;
    case 7:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setInterestamount(value);
      break;
    case 8:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setTenordays(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.BorrowingIssuanceProperty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.BorrowingIssuanceProperty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.BorrowingIssuanceProperty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingIssuanceProperty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBorrowingtokenaddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getCollateraltokenaddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getBorrowingamount();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getCollateralratio();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getCollateralamount();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getInterestrate();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getInterestamount();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getTenordays();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
};


/**
 * optional solidity.address borrowingTokenAddress = 1;
 * @return {?proto.solidity.address}
 */
proto.BorrowingIssuanceProperty.prototype.getBorrowingtokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 1));
};


/** @param {?proto.solidity.address|undefined} value */
proto.BorrowingIssuanceProperty.prototype.setBorrowingtokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingIssuanceProperty.prototype.clearBorrowingtokenaddress = function() {
  this.setBorrowingtokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingIssuanceProperty.prototype.hasBorrowingtokenaddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional solidity.address collateralTokenAddress = 2;
 * @return {?proto.solidity.address}
 */
proto.BorrowingIssuanceProperty.prototype.getCollateraltokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 2));
};


/** @param {?proto.solidity.address|undefined} value */
proto.BorrowingIssuanceProperty.prototype.setCollateraltokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingIssuanceProperty.prototype.clearCollateraltokenaddress = function() {
  this.setCollateraltokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingIssuanceProperty.prototype.hasCollateraltokenaddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional solidity.uint256 borrowingAmount = 3;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingIssuanceProperty.prototype.getBorrowingamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 3));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingIssuanceProperty.prototype.setBorrowingamount = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingIssuanceProperty.prototype.clearBorrowingamount = function() {
  this.setBorrowingamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingIssuanceProperty.prototype.hasBorrowingamount = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional solidity.uint256 collateralRatio = 4;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingIssuanceProperty.prototype.getCollateralratio = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 4));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingIssuanceProperty.prototype.setCollateralratio = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingIssuanceProperty.prototype.clearCollateralratio = function() {
  this.setCollateralratio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingIssuanceProperty.prototype.hasCollateralratio = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional solidity.uint256 collateralAmount = 5;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingIssuanceProperty.prototype.getCollateralamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 5));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingIssuanceProperty.prototype.setCollateralamount = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingIssuanceProperty.prototype.clearCollateralamount = function() {
  this.setCollateralamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingIssuanceProperty.prototype.hasCollateralamount = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional solidity.uint256 interestRate = 6;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingIssuanceProperty.prototype.getInterestrate = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 6));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingIssuanceProperty.prototype.setInterestrate = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingIssuanceProperty.prototype.clearInterestrate = function() {
  this.setInterestrate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingIssuanceProperty.prototype.hasInterestrate = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional solidity.uint256 interestAmount = 7;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingIssuanceProperty.prototype.getInterestamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 7));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingIssuanceProperty.prototype.setInterestamount = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingIssuanceProperty.prototype.clearInterestamount = function() {
  this.setInterestamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingIssuanceProperty.prototype.hasInterestamount = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional solidity.uint256 tenorDays = 8;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingIssuanceProperty.prototype.getTenordays = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 8));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingIssuanceProperty.prototype.setTenordays = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingIssuanceProperty.prototype.clearTenordays = function() {
  this.setTenordays(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingIssuanceProperty.prototype.hasTenordays = function() {
  return jspb.Message.getField(this, 8) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.BorrowingEngagementProperty.prototype.toObject = function(opt_includeInstance) {
  return proto.BorrowingEngagementProperty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.BorrowingEngagementProperty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingEngagementProperty.toObject = function(includeInstance, msg) {
  var f, obj = {
    loanstate: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.BorrowingEngagementProperty}
 */
proto.BorrowingEngagementProperty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.BorrowingEngagementProperty;
  return proto.BorrowingEngagementProperty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.BorrowingEngagementProperty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.BorrowingEngagementProperty}
 */
proto.BorrowingEngagementProperty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.BorrowingEngagementProperty.LoanState} */ (reader.readEnum());
      msg.setLoanstate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.BorrowingEngagementProperty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.BorrowingEngagementProperty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.BorrowingEngagementProperty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingEngagementProperty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLoanstate();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.BorrowingEngagementProperty.LoanState = {
  LOANSTATEUNKNOWN: 0,
  UNPAID: 1,
  REPAID: 2,
  DELINQUENT: 3
};

/**
 * optional LoanState loanState = 1;
 * @return {!proto.BorrowingEngagementProperty.LoanState}
 */
proto.BorrowingEngagementProperty.prototype.getLoanstate = function() {
  return /** @type {!proto.BorrowingEngagementProperty.LoanState} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.BorrowingEngagementProperty.LoanState} value */
proto.BorrowingEngagementProperty.prototype.setLoanstate = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


goog.object.extend(exports, proto);
