/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SolidityTypes_pb = require('./SolidityTypes_pb.js');
goog.object.extend(proto, SolidityTypes_pb);
var Payables_pb = require('./Payables_pb.js');
goog.object.extend(proto, Payables_pb);
goog.exportSymbol('proto.EngagementProperty', null, global);
goog.exportSymbol('proto.EngagementProperty.EngagementState', null, global);
goog.exportSymbol('proto.IssuanceProperty', null, global);
goog.exportSymbol('proto.IssuanceProperty.IssuanceState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.IssuanceProperty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.IssuanceProperty.repeatedFields_, null);
};
goog.inherits(proto.IssuanceProperty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.IssuanceProperty.displayName = 'proto.IssuanceProperty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.EngagementProperty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.EngagementProperty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.EngagementProperty.displayName = 'proto.EngagementProperty';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.IssuanceProperty.repeatedFields_ = [11,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.IssuanceProperty.prototype.toObject = function(opt_includeInstance) {
  return proto.IssuanceProperty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.IssuanceProperty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.IssuanceProperty.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuanceid: (f = msg.getIssuanceid()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    instrumentid: (f = msg.getInstrumentid()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    makeraddress: (f = msg.getMakeraddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    issuancecreationtimestamp: (f = msg.getIssuancecreationtimestamp()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    issuanceduetimestamp: (f = msg.getIssuanceduetimestamp()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    issuancecanceltimestamp: (f = msg.getIssuancecanceltimestamp()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    issuancecompletetimestamp: (f = msg.getIssuancecompletetimestamp()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    completionratio: (f = msg.getCompletionratio()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    issuancestate: jspb.Message.getFieldWithDefault(msg, 9, 0),
    issuancecustomproperty: msg.getIssuancecustomproperty_asB64(),
    engagementsList: jspb.Message.toObjectList(msg.getEngagementsList(),
    proto.EngagementProperty.toObject, includeInstance),
    payablesList: jspb.Message.toObjectList(msg.getPayablesList(),
    Payables_pb.Payable.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.IssuanceProperty}
 */
proto.IssuanceProperty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.IssuanceProperty;
  return proto.IssuanceProperty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.IssuanceProperty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.IssuanceProperty}
 */
proto.IssuanceProperty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setIssuanceid(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setInstrumentid(value);
      break;
    case 3:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setMakeraddress(value);
      break;
    case 4:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setIssuancecreationtimestamp(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setIssuanceduetimestamp(value);
      break;
    case 6:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setIssuancecanceltimestamp(value);
      break;
    case 7:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setIssuancecompletetimestamp(value);
      break;
    case 8:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCompletionratio(value);
      break;
    case 9:
      var value = /** @type {!proto.IssuanceProperty.IssuanceState} */ (reader.readEnum());
      msg.setIssuancestate(value);
      break;
    case 10:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setIssuancecustomproperty(value);
      break;
    case 11:
      var value = new proto.EngagementProperty;
      reader.readMessage(value,proto.EngagementProperty.deserializeBinaryFromReader);
      msg.addEngagements(value);
      break;
    case 12:
      var value = new Payables_pb.Payable;
      reader.readMessage(value,Payables_pb.Payable.deserializeBinaryFromReader);
      msg.addPayables(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.IssuanceProperty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.IssuanceProperty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.IssuanceProperty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.IssuanceProperty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuanceid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getInstrumentid();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getMakeraddress();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getIssuancecreationtimestamp();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getIssuanceduetimestamp();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getIssuancecanceltimestamp();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getIssuancecompletetimestamp();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getCompletionratio();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getIssuancestate();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getIssuancecustomproperty_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      10,
      f
    );
  }
  f = message.getEngagementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.EngagementProperty.serializeBinaryToWriter
    );
  }
  f = message.getPayablesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      Payables_pb.Payable.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.IssuanceProperty.IssuanceState = {
  ISSUANCESTATEUNKNOWN: 0,
  INITIATED: 1,
  ENGAGEABLE: 2,
  CANCELLED: 3,
  COMPLETE: 4
};

/**
 * optional solidity.uint256 issuanceId = 1;
 * @return {?proto.solidity.uint256}
 */
proto.IssuanceProperty.prototype.getIssuanceid = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 1));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.IssuanceProperty.prototype.setIssuanceid = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.IssuanceProperty.prototype.clearIssuanceid = function() {
  this.setIssuanceid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.IssuanceProperty.prototype.hasIssuanceid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional solidity.uint256 instrumentId = 2;
 * @return {?proto.solidity.uint256}
 */
proto.IssuanceProperty.prototype.getInstrumentid = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 2));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.IssuanceProperty.prototype.setInstrumentid = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.IssuanceProperty.prototype.clearInstrumentid = function() {
  this.setInstrumentid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.IssuanceProperty.prototype.hasInstrumentid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional solidity.address makerAddress = 3;
 * @return {?proto.solidity.address}
 */
proto.IssuanceProperty.prototype.getMakeraddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 3));
};


/** @param {?proto.solidity.address|undefined} value */
proto.IssuanceProperty.prototype.setMakeraddress = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.IssuanceProperty.prototype.clearMakeraddress = function() {
  this.setMakeraddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.IssuanceProperty.prototype.hasMakeraddress = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional solidity.uint256 issuanceCreationTimestamp = 4;
 * @return {?proto.solidity.uint256}
 */
proto.IssuanceProperty.prototype.getIssuancecreationtimestamp = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 4));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.IssuanceProperty.prototype.setIssuancecreationtimestamp = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.IssuanceProperty.prototype.clearIssuancecreationtimestamp = function() {
  this.setIssuancecreationtimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.IssuanceProperty.prototype.hasIssuancecreationtimestamp = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional solidity.uint256 issuanceDueTimestamp = 5;
 * @return {?proto.solidity.uint256}
 */
proto.IssuanceProperty.prototype.getIssuanceduetimestamp = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 5));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.IssuanceProperty.prototype.setIssuanceduetimestamp = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.IssuanceProperty.prototype.clearIssuanceduetimestamp = function() {
  this.setIssuanceduetimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.IssuanceProperty.prototype.hasIssuanceduetimestamp = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional solidity.uint256 issuanceCancelTimestamp = 6;
 * @return {?proto.solidity.uint256}
 */
proto.IssuanceProperty.prototype.getIssuancecanceltimestamp = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 6));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.IssuanceProperty.prototype.setIssuancecanceltimestamp = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.IssuanceProperty.prototype.clearIssuancecanceltimestamp = function() {
  this.setIssuancecanceltimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.IssuanceProperty.prototype.hasIssuancecanceltimestamp = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional solidity.uint256 issuanceCompleteTimestamp = 7;
 * @return {?proto.solidity.uint256}
 */
proto.IssuanceProperty.prototype.getIssuancecompletetimestamp = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 7));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.IssuanceProperty.prototype.setIssuancecompletetimestamp = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.IssuanceProperty.prototype.clearIssuancecompletetimestamp = function() {
  this.setIssuancecompletetimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.IssuanceProperty.prototype.hasIssuancecompletetimestamp = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional solidity.uint256 completionRatio = 8;
 * @return {?proto.solidity.uint256}
 */
proto.IssuanceProperty.prototype.getCompletionratio = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 8));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.IssuanceProperty.prototype.setCompletionratio = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.IssuanceProperty.prototype.clearCompletionratio = function() {
  this.setCompletionratio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.IssuanceProperty.prototype.hasCompletionratio = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional IssuanceState issuanceState = 9;
 * @return {!proto.IssuanceProperty.IssuanceState}
 */
proto.IssuanceProperty.prototype.getIssuancestate = function() {
  return /** @type {!proto.IssuanceProperty.IssuanceState} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {!proto.IssuanceProperty.IssuanceState} value */
proto.IssuanceProperty.prototype.setIssuancestate = function(value) {
  jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional bytes issuanceCustomProperty = 10;
 * @return {!(string|Uint8Array)}
 */
proto.IssuanceProperty.prototype.getIssuancecustomproperty = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * optional bytes issuanceCustomProperty = 10;
 * This is a type-conversion wrapper around `getIssuancecustomproperty()`
 * @return {string}
 */
proto.IssuanceProperty.prototype.getIssuancecustomproperty_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getIssuancecustomproperty()));
};


/**
 * optional bytes issuanceCustomProperty = 10;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getIssuancecustomproperty()`
 * @return {!Uint8Array}
 */
proto.IssuanceProperty.prototype.getIssuancecustomproperty_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getIssuancecustomproperty()));
};


/** @param {!(string|Uint8Array)} value */
proto.IssuanceProperty.prototype.setIssuancecustomproperty = function(value) {
  jspb.Message.setProto3BytesField(this, 10, value);
};


/**
 * repeated EngagementProperty engagements = 11;
 * @return {!Array<!proto.EngagementProperty>}
 */
proto.IssuanceProperty.prototype.getEngagementsList = function() {
  return /** @type{!Array<!proto.EngagementProperty>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.EngagementProperty, 11));
};


/** @param {!Array<!proto.EngagementProperty>} value */
proto.IssuanceProperty.prototype.setEngagementsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.EngagementProperty=} opt_value
 * @param {number=} opt_index
 * @return {!proto.EngagementProperty}
 */
proto.IssuanceProperty.prototype.addEngagements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.EngagementProperty, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.IssuanceProperty.prototype.clearEngagementsList = function() {
  this.setEngagementsList([]);
};


/**
 * repeated Payable payables = 12;
 * @return {!Array<!proto.Payable>}
 */
proto.IssuanceProperty.prototype.getPayablesList = function() {
  return /** @type{!Array<!proto.Payable>} */ (
    jspb.Message.getRepeatedWrapperField(this, Payables_pb.Payable, 12));
};


/** @param {!Array<!proto.Payable>} value */
proto.IssuanceProperty.prototype.setPayablesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.Payable=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Payable}
 */
proto.IssuanceProperty.prototype.addPayables = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.Payable, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.IssuanceProperty.prototype.clearPayablesList = function() {
  this.setPayablesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.EngagementProperty.prototype.toObject = function(opt_includeInstance) {
  return proto.EngagementProperty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.EngagementProperty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.EngagementProperty.toObject = function(includeInstance, msg) {
  var f, obj = {
    engagementid: (f = msg.getEngagementid()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    takeraddress: (f = msg.getTakeraddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    engagementcreationtimestamp: (f = msg.getEngagementcreationtimestamp()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    engagementduetimestamp: (f = msg.getEngagementduetimestamp()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    engagementcanceltimestamp: (f = msg.getEngagementcanceltimestamp()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    engagementcompletetimestamp: (f = msg.getEngagementcompletetimestamp()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    engagementstate: jspb.Message.getFieldWithDefault(msg, 7, 0),
    engagementcustomproperty: msg.getEngagementcustomproperty_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.EngagementProperty}
 */
proto.EngagementProperty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.EngagementProperty;
  return proto.EngagementProperty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.EngagementProperty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.EngagementProperty}
 */
proto.EngagementProperty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setEngagementid(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setTakeraddress(value);
      break;
    case 3:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setEngagementcreationtimestamp(value);
      break;
    case 4:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setEngagementduetimestamp(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setEngagementcanceltimestamp(value);
      break;
    case 6:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setEngagementcompletetimestamp(value);
      break;
    case 7:
      var value = /** @type {!proto.EngagementProperty.EngagementState} */ (reader.readEnum());
      msg.setEngagementstate(value);
      break;
    case 8:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEngagementcustomproperty(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.EngagementProperty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.EngagementProperty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.EngagementProperty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.EngagementProperty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEngagementid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getTakeraddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getEngagementcreationtimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getEngagementduetimestamp();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getEngagementcanceltimestamp();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getEngagementcompletetimestamp();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getEngagementstate();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getEngagementcustomproperty_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      8,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.EngagementProperty.EngagementState = {
  ENGAGEMENTSTATEUNKNOWN: 0,
  INITIATED: 1,
  ACTIVE: 2,
  CANCELLED: 3,
  COMPLETE: 4
};

/**
 * optional solidity.uint256 engagementId = 1;
 * @return {?proto.solidity.uint256}
 */
proto.EngagementProperty.prototype.getEngagementid = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 1));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.EngagementProperty.prototype.setEngagementid = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.EngagementProperty.prototype.clearEngagementid = function() {
  this.setEngagementid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.EngagementProperty.prototype.hasEngagementid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional solidity.address takerAddress = 2;
 * @return {?proto.solidity.address}
 */
proto.EngagementProperty.prototype.getTakeraddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 2));
};


/** @param {?proto.solidity.address|undefined} value */
proto.EngagementProperty.prototype.setTakeraddress = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.EngagementProperty.prototype.clearTakeraddress = function() {
  this.setTakeraddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.EngagementProperty.prototype.hasTakeraddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional solidity.uint256 engagementCreationTimestamp = 3;
 * @return {?proto.solidity.uint256}
 */
proto.EngagementProperty.prototype.getEngagementcreationtimestamp = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 3));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.EngagementProperty.prototype.setEngagementcreationtimestamp = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.EngagementProperty.prototype.clearEngagementcreationtimestamp = function() {
  this.setEngagementcreationtimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.EngagementProperty.prototype.hasEngagementcreationtimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional solidity.uint256 engagementDueTimestamp = 4;
 * @return {?proto.solidity.uint256}
 */
proto.EngagementProperty.prototype.getEngagementduetimestamp = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 4));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.EngagementProperty.prototype.setEngagementduetimestamp = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.EngagementProperty.prototype.clearEngagementduetimestamp = function() {
  this.setEngagementduetimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.EngagementProperty.prototype.hasEngagementduetimestamp = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional solidity.uint256 engagementCancelTimestamp = 5;
 * @return {?proto.solidity.uint256}
 */
proto.EngagementProperty.prototype.getEngagementcanceltimestamp = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 5));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.EngagementProperty.prototype.setEngagementcanceltimestamp = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.EngagementProperty.prototype.clearEngagementcanceltimestamp = function() {
  this.setEngagementcanceltimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.EngagementProperty.prototype.hasEngagementcanceltimestamp = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional solidity.uint256 engagementCompleteTimestamp = 6;
 * @return {?proto.solidity.uint256}
 */
proto.EngagementProperty.prototype.getEngagementcompletetimestamp = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 6));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.EngagementProperty.prototype.setEngagementcompletetimestamp = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.EngagementProperty.prototype.clearEngagementcompletetimestamp = function() {
  this.setEngagementcompletetimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.EngagementProperty.prototype.hasEngagementcompletetimestamp = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional EngagementState engagementState = 7;
 * @return {!proto.EngagementProperty.EngagementState}
 */
proto.EngagementProperty.prototype.getEngagementstate = function() {
  return /** @type {!proto.EngagementProperty.EngagementState} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {!proto.EngagementProperty.EngagementState} value */
proto.EngagementProperty.prototype.setEngagementstate = function(value) {
  jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional bytes engagementCustomProperty = 8;
 * @return {!(string|Uint8Array)}
 */
proto.EngagementProperty.prototype.getEngagementcustomproperty = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * optional bytes engagementCustomProperty = 8;
 * This is a type-conversion wrapper around `getEngagementcustomproperty()`
 * @return {string}
 */
proto.EngagementProperty.prototype.getEngagementcustomproperty_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEngagementcustomproperty()));
};


/**
 * optional bytes engagementCustomProperty = 8;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEngagementcustomproperty()`
 * @return {!Uint8Array}
 */
proto.EngagementProperty.prototype.getEngagementcustomproperty_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEngagementcustomproperty()));
};


/** @param {!(string|Uint8Array)} value */
proto.EngagementProperty.prototype.setEngagementcustomproperty = function(value) {
  jspb.Message.setProto3BytesField(this, 8, value);
};


goog.object.extend(exports, proto);
